//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cardtable_use
    {
        public int id { get; set; }
        public string name { get; set; }
        public string link { get; set; }
        public string situation { get; set; }
        public string obstacle { get; set; }
        public string advice { get; set; }
    }
}
