//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class readertable
    {
        public int id { get; set; }
        public string name { get; set; }
        public string position { get; set; }
        public string link { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string detail_1 { get; set; }
        public string detail_2 { get; set; }
        public string detail_3 { get; set; }
        public string detail_4 { get; set; }
        public string img { get; set; }
    }
}
