//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace WebApplication2.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TAROTWEBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TAROTWEBEntities object using the connection string found in the 'TAROTWEBEntities' section of the application configuration file.
        /// </summary>
        public TAROTWEBEntities() : base("name=TAROTWEBEntities", "TAROTWEBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TAROTWEBEntities object.
        /// </summary>
        public TAROTWEBEntities(string connectionString) : base(connectionString, "TAROTWEBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TAROTWEBEntities object.
        /// </summary>
        public TAROTWEBEntities(EntityConnection connection) : base(connection, "TAROTWEBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<cardtable> cardtables
        {
            get
            {
                if ((_cardtables == null))
                {
                    _cardtables = base.CreateObjectSet<cardtable>("cardtables");
                }
                return _cardtables;
            }
        }
        private ObjectSet<cardtable> _cardtables;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<menutable> menutables
        {
            get
            {
                if ((_menutables == null))
                {
                    _menutables = base.CreateObjectSet<menutable>("menutables");
                }
                return _menutables;
            }
        }
        private ObjectSet<menutable> _menutables;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<newstable> newstables
        {
            get
            {
                if ((_newstables == null))
                {
                    _newstables = base.CreateObjectSet<newstable>("newstables");
                }
                return _newstables;
            }
        }
        private ObjectSet<newstable> _newstables;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the cardtables EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocardtables(cardtable cardtable)
        {
            base.AddObject("cardtables", cardtable);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the menutables EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomenutables(menutable menutable)
        {
            base.AddObject("menutables", menutable);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the newstables EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTonewstables(newstable newstable)
        {
            base.AddObject("newstables", newstable);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TAROTWEBModel2", Name="cardtable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class cardtable : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new cardtable object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static cardtable Createcardtable(global::System.Int32 id)
        {
            cardtable cardtable = new cardtable();
            cardtable.id = id;
            return cardtable;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String link
        {
            get
            {
                return _link;
            }
            set
            {
                OnlinkChanging(value);
                ReportPropertyChanging("link");
                _link = StructuralObject.SetValidValue(value, true, "link");
                ReportPropertyChanged("link");
                OnlinkChanged();
            }
        }
        private global::System.String _link;
        partial void OnlinkChanging(global::System.String value);
        partial void OnlinkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String alt
        {
            get
            {
                return _alt;
            }
            set
            {
                OnaltChanging(value);
                ReportPropertyChanging("alt");
                _alt = StructuralObject.SetValidValue(value, true, "alt");
                ReportPropertyChanged("alt");
                OnaltChanged();
            }
        }
        private global::System.String _alt;
        partial void OnaltChanging(global::System.String value);
        partial void OnaltChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descripsion_u
        {
            get
            {
                return _descripsion_u;
            }
            set
            {
                Ondescripsion_uChanging(value);
                ReportPropertyChanging("descripsion_u");
                _descripsion_u = StructuralObject.SetValidValue(value, true, "descripsion_u");
                ReportPropertyChanged("descripsion_u");
                Ondescripsion_uChanged();
            }
        }
        private global::System.String _descripsion_u;
        partial void Ondescripsion_uChanging(global::System.String value);
        partial void Ondescripsion_uChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descripsion_r
        {
            get
            {
                return _descripsion_r;
            }
            set
            {
                Ondescripsion_rChanging(value);
                ReportPropertyChanging("descripsion_r");
                _descripsion_r = StructuralObject.SetValidValue(value, true, "descripsion_r");
                ReportPropertyChanged("descripsion_r");
                Ondescripsion_rChanged();
            }
        }
        private global::System.String _descripsion_r;
        partial void Ondescripsion_rChanging(global::System.String value);
        partial void Ondescripsion_rChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String detail_u
        {
            get
            {
                return _detail_u;
            }
            set
            {
                Ondetail_uChanging(value);
                ReportPropertyChanging("detail_u");
                _detail_u = StructuralObject.SetValidValue(value, true, "detail_u");
                ReportPropertyChanged("detail_u");
                Ondetail_uChanged();
            }
        }
        private global::System.String _detail_u;
        partial void Ondetail_uChanging(global::System.String value);
        partial void Ondetail_uChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String detail_r
        {
            get
            {
                return _detail_r;
            }
            set
            {
                Ondetail_rChanging(value);
                ReportPropertyChanging("detail_r");
                _detail_r = StructuralObject.SetValidValue(value, true, "detail_r");
                ReportPropertyChanged("detail_r");
                Ondetail_rChanged();
            }
        }
        private global::System.String _detail_r;
        partial void Ondetail_rChanging(global::System.String value);
        partial void Ondetail_rChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TAROTWEBModel2", Name="menutable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class menutable : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new menutable object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static menutable Createmenutable(global::System.Int32 id)
        {
            menutable menutable = new menutable();
            menutable.id = id;
            return menutable;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String link
        {
            get
            {
                return _link;
            }
            set
            {
                OnlinkChanging(value);
                ReportPropertyChanging("link");
                _link = StructuralObject.SetValidValue(value, true, "link");
                ReportPropertyChanged("link");
                OnlinkChanged();
            }
        }
        private global::System.String _link;
        partial void OnlinkChanging(global::System.String value);
        partial void OnlinkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String meta
        {
            get
            {
                return _meta;
            }
            set
            {
                OnmetaChanging(value);
                ReportPropertyChanging("meta");
                _meta = StructuralObject.SetValidValue(value, true, "meta");
                ReportPropertyChanged("meta");
                OnmetaChanged();
            }
        }
        private global::System.String _meta;
        partial void OnmetaChanging(global::System.String value);
        partial void OnmetaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> hide
        {
            get
            {
                return _hide;
            }
            set
            {
                OnhideChanging(value);
                ReportPropertyChanging("hide");
                _hide = StructuralObject.SetValidValue(value, "hide");
                ReportPropertyChanged("hide");
                OnhideChanged();
            }
        }
        private Nullable<global::System.Boolean> _hide;
        partial void OnhideChanging(Nullable<global::System.Boolean> value);
        partial void OnhideChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> order
        {
            get
            {
                return _order;
            }
            set
            {
                OnorderChanging(value);
                ReportPropertyChanging("order");
                _order = StructuralObject.SetValidValue(value, "order");
                ReportPropertyChanged("order");
                OnorderChanged();
            }
        }
        private Nullable<global::System.Int32> _order;
        partial void OnorderChanging(Nullable<global::System.Int32> value);
        partial void OnorderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> datebegin
        {
            get
            {
                return _datebegin;
            }
            set
            {
                OndatebeginChanging(value);
                ReportPropertyChanging("datebegin");
                _datebegin = StructuralObject.SetValidValue(value, "datebegin");
                ReportPropertyChanged("datebegin");
                OndatebeginChanged();
            }
        }
        private Nullable<global::System.DateTime> _datebegin;
        partial void OndatebeginChanging(Nullable<global::System.DateTime> value);
        partial void OndatebeginChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TAROTWEBModel2", Name="newstable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class newstable : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new newstable object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static newstable Createnewstable(global::System.Int32 id)
        {
            newstable newstable = new newstable();
            newstable.id = id;
            return newstable;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String link
        {
            get
            {
                return _link;
            }
            set
            {
                OnlinkChanging(value);
                ReportPropertyChanging("link");
                _link = StructuralObject.SetValidValue(value, true, "link");
                ReportPropertyChanged("link");
                OnlinkChanged();
            }
        }
        private global::System.String _link;
        partial void OnlinkChanging(global::System.String value);
        partial void OnlinkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String meta
        {
            get
            {
                return _meta;
            }
            set
            {
                OnmetaChanging(value);
                ReportPropertyChanging("meta");
                _meta = StructuralObject.SetValidValue(value, true, "meta");
                ReportPropertyChanged("meta");
                OnmetaChanged();
            }
        }
        private global::System.String _meta;
        partial void OnmetaChanging(global::System.String value);
        partial void OnmetaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> hide
        {
            get
            {
                return _hide;
            }
            set
            {
                OnhideChanging(value);
                ReportPropertyChanging("hide");
                _hide = StructuralObject.SetValidValue(value, "hide");
                ReportPropertyChanged("hide");
                OnhideChanged();
            }
        }
        private Nullable<global::System.Boolean> _hide;
        partial void OnhideChanging(Nullable<global::System.Boolean> value);
        partial void OnhideChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> order
        {
            get
            {
                return _order;
            }
            set
            {
                OnorderChanging(value);
                ReportPropertyChanging("order");
                _order = StructuralObject.SetValidValue(value, "order");
                ReportPropertyChanged("order");
                OnorderChanged();
            }
        }
        private Nullable<global::System.Int32> _order;
        partial void OnorderChanging(Nullable<global::System.Int32> value);
        partial void OnorderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> datebegin
        {
            get
            {
                return _datebegin;
            }
            set
            {
                OndatebeginChanging(value);
                ReportPropertyChanging("datebegin");
                _datebegin = StructuralObject.SetValidValue(value, "datebegin");
                ReportPropertyChanged("datebegin");
                OndatebeginChanged();
            }
        }
        private Nullable<global::System.DateTime> _datebegin;
        partial void OndatebeginChanging(Nullable<global::System.DateTime> value);
        partial void OndatebeginChanged();

        #endregion

    }

    #endregion

}
